[2024-02-03T03:42:17.429+0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_score.test_model manual__2024-02-02T23:41:57.731278+00:00 [queued]>
[2024-02-03T03:42:17.435+0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_score.test_model manual__2024-02-02T23:41:57.731278+00:00 [queued]>
[2024-02-03T03:42:17.435+0400] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-03T03:42:17.445+0400] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): test_model> on 2024-02-02 23:41:57.731278+00:00
[2024-02-03T03:42:17.449+0400] {standard_task_runner.py:60} INFO - Started process 1050 to run task
[2024-02-03T03:42:17.451+0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'iris_score', 'test_model', 'manual__2024-02-02T23:41:57.731278+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/iris_score.py', '--cfg-path', '/tmp/tmppsnz1kh_']
[2024-02-03T03:42:17.453+0400] {standard_task_runner.py:88} INFO - Job 37: Subtask test_model
[2024-02-03T03:42:17.481+0400] {task_command.py:423} INFO - Running <TaskInstance: iris_score.test_model manual__2024-02-02T23:41:57.731278+00:00 [running]> on host WIN-IO5IBOGGQDO.localdomain
[2024-02-03T03:42:17.519+0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='iris_score' AIRFLOW_CTX_TASK_ID='test_model' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T23:41:57.731278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-02T23:41:57.731278+00:00'
[2024-02-03T03:42:17.520+0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-03T03:42:17.521+0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/reurairin/projects/urfu/urfu_3s_mlops-3/scripts/test_model.py']
[2024-02-03T03:42:17.527+0400] {subprocess.py:86} INFO - Output:
[2024-02-03T03:42:18.283+0400] {subprocess.py:93} INFO - 2024/02/03 03:42:18 INFO mlflow.tracking.fluent: Experiment with name 'test_model' does not exist. Creating a new experiment.
[2024-02-03T03:42:18.671+0400] {subprocess.py:93} INFO - score= 1.0
[2024-02-03T03:42:18.880+0400] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-03T03:42:18.894+0400] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=iris_score, task_id=test_model, execution_date=20240202T234157, start_date=20240202T234217, end_date=20240202T234218
[2024-02-03T03:42:18.912+0400] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-03T03:42:18.950+0400] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
