[2024-02-03T03:40:18.198+0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_score.train_model manual__2024-02-02T23:40:04.357518+00:00 [queued]>
[2024-02-03T03:40:18.202+0400] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_score.train_model manual__2024-02-02T23:40:04.357518+00:00 [queued]>
[2024-02-03T03:40:18.202+0400] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-02-03T03:40:18.212+0400] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): train_model> on 2024-02-02 23:40:04.357518+00:00
[2024-02-03T03:40:18.215+0400] {standard_task_runner.py:60} INFO - Started process 325 to run task
[2024-02-03T03:40:18.217+0400] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'iris_score', 'train_model', 'manual__2024-02-02T23:40:04.357518+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/iris_score.py', '--cfg-path', '/tmp/tmpwtwi1qbl']
[2024-02-03T03:40:18.218+0400] {standard_task_runner.py:88} INFO - Job 32: Subtask train_model
[2024-02-03T03:40:18.239+0400] {task_command.py:423} INFO - Running <TaskInstance: iris_score.train_model manual__2024-02-02T23:40:04.357518+00:00 [running]> on host WIN-IO5IBOGGQDO.localdomain
[2024-02-03T03:40:18.273+0400] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='iris_score' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-02-02T23:40:04.357518+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-02T23:40:04.357518+00:00'
[2024-02-03T03:40:18.274+0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-03T03:40:18.275+0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/reurairin/projects/urfu/urfu_3s_mlops-3/scripts/train_model.py']
[2024-02-03T03:40:18.279+0400] {subprocess.py:86} INFO - Output:
[2024-02-03T03:40:19.320+0400] {subprocess.py:93} INFO - 2024/02/03 03:40:19 INFO mlflow.tracking.fluent: Experiment with name 'train_model' does not exist. Creating a new experiment.
[2024-02-03T03:40:19.397+0400] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-02-03T03:40:19.397+0400] {subprocess.py:93} INFO -   File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/scripts/train_model.py", line 13, in <module>
[2024-02-03T03:40:19.397+0400] {subprocess.py:93} INFO -     model = KNeighborsClassifier(n_neighbors=5, random_state=42)
[2024-02-03T03:40:19.397+0400] {subprocess.py:93} INFO - TypeError: KNeighborsClassifier.__init__() got an unexpected keyword argument 'random_state'
[2024-02-03T03:40:19.617+0400] {subprocess.py:97} INFO - Command exited with return code 1
[2024-02-03T03:40:19.622+0400] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/reurairin/projects/urfu/urfu_3s_mlops-3/env/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-03T03:40:19.624+0400] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=iris_score, task_id=train_model, execution_date=20240202T234004, start_date=20240202T234018, end_date=20240202T234019
[2024-02-03T03:40:19.633+0400] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task train_model (Bash command failed. The command returned a non-zero exit code 1.; 325)
[2024-02-03T03:40:19.673+0400] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-03T03:40:19.688+0400] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
